[package]
name = "heapquery"
version = "0.1.0"
authors = ["hsiaosiyuan0 <hsiaosiyuan0@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
rusqlite = "0.24.2"
clap = "2.33.3"
